### PR TITLE
parallel bug and code duplication/simplification

### PR DESCRIPTION
**Pull request by vincentarelbundock**
Thanks for your great work on preText! This is going to be a very useful package. 

Parallel processing does not seem to work currently. This PR fixes some issues related to that, and also simplifies/de-duplicates a lot of the code.

1. Parallel now works.
2. Recent versions of quanteda changed argument names. 
3. parallel_preprocess returned run time rather than the dfm itself. [edit: i understand why now, see below]
4. Code simplication: simplify the conditionals in parallel_preprocessing(). 
5. Code de-duplication. Single core and parallel processing should both use the same internal function to create a dfm. This removes about 100 lines of code, and creates a single point of entry for modifying the dfm building code. Much easier to debug and improve.
6. No need for a parallel argument. Just use parallel if cores > 1.
7. mclapply is easier to use than makeCluster

I couldn't find an actual test suite, but things look good on my computer.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
This is one of those cases where looking at the diff file isn't too helpful. But just read these two files and everything should be clear.

https://github.com/vincentarelbundock/preText/blob/master/R/factorial_preprocessing.R
https://github.com/vincentarelbundock/preText/blob/master/R/parallel_preprocess.R

**Comment by vincentarelbundock** [comment]
I figured out why ``parallel_preprocessing()`` was returning compute time rather than the dfm. Modified the code to allow saving intermediate dfm to file instead of keeping it all in memory.

**Comment by vincentarelbundock** [comment]
Maybe this should be in a different PR, but I split-off the `expand.grid` code to create the data.frame of factorial choices and labels into its own function. Doing this allows you to expose a new `choices` argument to users.

Use-case: For theoretically-motivated reasons, Vincent only cares about combinations of pre-processing choices that (a) use ngrams, and (b) remove numbers. To do this, he writes:

```
library(preText)
library(quanteda)
corp <- data_corpus_inaugural
choices <- list('removePunctuation' = c(TRUE, FALSE),
                'removeNumbers' = TRUE,
                'lowercase' = c(TRUE, FALSE),
                'stem' = c(TRUE, FALSE),
                'removeStopwords' = c(TRUE, FALSE),
                'infrequent_terms' = c(TRUE, FALSE),
                'use_ngrams' = TRUE)
z = preText::factorial_preprocessing(corp, use_ngrams = FALSE, cores = 5,
                                     return_results = FALSE, choices = choices)
```

**Comment by matthewjdenny** [comment]
Hi Vincent,

Thanks for your interest in PreText! Can you tell me a bit more about parallel preprocessing not working? It seems to be currently working on my computer but perhaps I have missed something. Can you provide a replicable example?

Also, you replaced parallel::clusterApplyLB with parallel::mclapply in your PR which is not portable to windows (see:  https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/mclapply.html). Furthermore, the different combinations can take wildly different amounts of time so load balancing is actually really nice to have.

I am still not sure I follow this point, could you elaborate?:

> I figured out why parallel_preprocessing() was returning compute time rather than the dfm. Modified the code to allow saving intermediate dfm to file instead of keeping it all in memory.

The code currently saves the dfm's to file automatically because on some OS's (e.g. CentOS 6, if I recall correctly), returning a quanteda::dfm object through parallel::clusterApplyLB results in an error. 

I really appreciate your modifications and some of them are nice/make a lot of sense. However, I am still concerned about some of the cross platform implications (tests are also failing, would need to track those down, have you run R CMD Check?). Perhaps we could Skype next week or something (will you be at PolMeth?) and discuss this stuff.

Best,
Matt

**Comment by vincentarelbundock** [comment]
The initial problem really seems to be related to `makeCluster`. Here’s what I get using Github Master on an Ubuntu machine:

```
> library(preText)
> library(quanteda)
> corp <- data_corpus_inaugural
> z = preText::factorial_preprocessing(corp, use_ngrams = FALSE, parallel = TRUE, cores = 5)
Preprocessing 58 documents 64 different ways...
Preprocessing documents 64 different ways on 5 cores. This may take a while...
Error in checkForRemoteErrors(val) :
  64 nodes produced errors; first error: argument is of length zero
>
```

I didn’t realize mclapply wouldn’t work on Windows; that’s obviously a big problem. I tried using makeCluster (or makeForkCluster) using different settings on my machine but couldn’t get it to work (it spit out some `sendData` error).  So what I’ve done is use a conditional based on OS type: use mclapply if OS type is unix (so for Mac or linux), and your old version otherwise.

The quote you wanted clarification on was just me not understanding why you would `return(ret)` here: https://github.com/matthewjdenny/preText/blob/master/R/parallel_preprocess.R#L66

I don’t know why R CMD check fails on Travis. The log says that the simple `testhat` example fails, but it works well when I just run `testthat` (i.e., not as part of R CMD check). 

I’m happy to skype on Mon-Tue-Wed 9 to 16 EST, but will be travelling from then on until the end of July. And Polmeth isn’t in the cards this year, unfortunately.

**Comment by vincentarelbundock** [comment]
And I think you can get load balancing in `mclapply` using `mc.preschedule = FALSE`.

**Comment by vincentarelbundock** [comment]
I fixed the test breakage.

Also, I set up a Linode machine which you can access by SSH to test the parallel code on a linux computer. Will send you the login names and passwords by email.

**Pull request closed without merging**
